package mediator.handlers;

public enum Request {
    GETUSERCART,
    ADDTOCART,
    DELETEITEM,
    GETDEALS,
    GETDEALSBYPRICE,
    GETDEALSBYNAME,
    GETDEALSBYTYPE,
    GETDEALSBYPRICEANDNAME,
    GETDEALSBYPRICEANDTYPE,
    GETDEALSBYNAMEANDTYPE,
    GETFILTEREDDEALS,
    ADDDEAL,
    EDITDEAL,
    DELETEDEAL,
    APPLYDISCOUNT,
    ADDFEEDBACK
}
